version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: CoffeeMachine
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256	
    volumes :
      - pgdata:/var/lib/postgres/data/
    ports:
      - "5432:5432"
    restart: unless-stopped 

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@nomail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    restart: unless-stopped

volumes :
  pgdata:

